# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

gibbsSamplerC <- function(nMC, y, X, a = 1.1, b = 1.1, kappa = 0.1) {
    .Call('bayesMCMC_gibbsSamplerC', PACKAGE = 'bayesMCMC', nMC, y, X, a, b, kappa)
}

lpi <- function(y, beta, sigmasq, X) {
    .Call('bayesMCMC_lpi', PACKAGE = 'bayesMCMC', y, beta, sigmasq, X)
}

upd <- function(p, oldbeta, cholesky, rnorms) {
    .Call('bayesMCMC_upd', PACKAGE = 'bayesMCMC', p, oldbeta, cholesky, rnorms)
}

RWMfunC <- function(nMC, y, X, stepsize = exp(-5)) {
    .Call('bayesMCMC_RWMfunC', PACKAGE = 'bayesMCMC', nMC, y, X, stepsize)
}


