// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>
#include <RcppEigen.h>

using namespace Rcpp;
using namespace Eigen;

// gibbsSamplerC
MatrixXd gibbsSamplerC(int nMC, VectorXd y, MatrixXd X, double a, double b, double kappa);
RcppExport SEXP bayesMCMC_gibbsSamplerC(SEXP nMCSEXP, SEXP ySEXP, SEXP XSEXP, SEXP aSEXP, SEXP bSEXP, SEXP kappaSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< int >::type nMC(nMCSEXP);
    Rcpp::traits::input_parameter< VectorXd >::type y(ySEXP);
    Rcpp::traits::input_parameter< MatrixXd >::type X(XSEXP);
    Rcpp::traits::input_parameter< double >::type a(aSEXP);
    Rcpp::traits::input_parameter< double >::type b(bSEXP);
    Rcpp::traits::input_parameter< double >::type kappa(kappaSEXP);
    __result = Rcpp::wrap(gibbsSamplerC(nMC, y, X, a, b, kappa));
    return __result;
END_RCPP
}
// lpi
double lpi(NumericVector y, NumericVector beta, double sigmasq, NumericMatrix X);
RcppExport SEXP bayesMCMC_lpi(SEXP ySEXP, SEXP betaSEXP, SEXP sigmasqSEXP, SEXP XSEXP) {
    BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< NumericVector >::type y(ySEXP);
    Rcpp::traits::input_parameter< NumericVector >::type beta(betaSEXP);
    Rcpp::traits::input_parameter< double >::type sigmasq(sigmasqSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type X(XSEXP);
    __result = Rcpp::wrap(lpi(y, beta, sigmasq, X));
    return __result;
END_RCPP
}
// upd
NumericVector upd(int p, NumericVector oldbeta, NumericMatrix cholesky, NumericVector rnorms);
RcppExport SEXP bayesMCMC_upd(SEXP pSEXP, SEXP oldbetaSEXP, SEXP choleskySEXP, SEXP rnormsSEXP) {
    BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< int >::type p(pSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type oldbeta(oldbetaSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type cholesky(choleskySEXP);
    Rcpp::traits::input_parameter< NumericVector >::type rnorms(rnormsSEXP);
    __result = Rcpp::wrap(upd(p, oldbeta, cholesky, rnorms));
    return __result;
END_RCPP
}
// RWMfunC
NumericMatrix RWMfunC(int nMC, NumericVector y, NumericMatrix X, double stepsize);
RcppExport SEXP bayesMCMC_RWMfunC(SEXP nMCSEXP, SEXP ySEXP, SEXP XSEXP, SEXP stepsizeSEXP) {
    BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< int >::type nMC(nMCSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type y(ySEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type X(XSEXP);
    Rcpp::traits::input_parameter< double >::type stepsize(stepsizeSEXP);
    __result = Rcpp::wrap(RWMfunC(nMC, y, X, stepsize));
    return __result;
END_RCPP
}

